apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaadin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaadin-app
  template:
    metadata:
      labels:
        app: vaadin-app
    spec:
      containers:
        - name: vaadin-container
#          image: praveenk212/vaadin-app:20250516-1156
          image:  praveenk212/vaadin-app:20250516-1300

          ports:
            - containerPort: 12345
          args: ["--port=12345", "--dbUrl=jdbc:postgresql://postgres:5432/mydb", "--dbUserName=pk", "--dbPass=mypassword"]
---
apiVersion: v1
kind: Service
metadata:
  name: vaadin-service
spec:
  selector:
    app: vaadin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 12345
  type: LoadBalancer
